name: restaurant_tour

sdkPath: .fvm/flutter_sdk

packages:
  - app
  - common/**
  - features/**

scripts:
  build_runner:
    run: melos exec -- "dart run build_runner build --delete-conflicting-outputs"
    description: Run `build_runner build` in all packages that have it.
    packageFilters:
      dependsOn: build_runner
  test:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run Dart/Flutter tests in all packages.

  test:dart:
    run: melos exec --concurrency=1 --fail-fast -- "dart test"
    description: Run Dart test in all dart packages.
    packageFilters:
      flutter: false
      dirExists: test
      ignore: "*example*"

  test:flutter:
    run: melos exec --concurrency=1 --fail-fast -- "flutter test --coverage --test-randomize-ordering-seed random"
    description: Run Flutter test in all flutter packages.
    packageFilters:
      flutter: true
      dirExists: test
      ignore: "*example*"

  test:flutterWithHtmlCoverage:
    run: melos exec --concurrency=1 --fail-fast "flutter test --coverage --test-randomize-ordering-seed random --reporter expanded && genhtml coverage/lcov.info --output-directory coverage/html && open coverage/html/index.html"
    description: Run Flutter test in all flutter packages with HTML coverage.
    packageFilters:
      flutter: true
      dirExists: test
      ignore: "*example*"

  test:integration:
    run: melos exec --concurrency=1 --fail-fast -- "flutter test integration_test"
    description: Run Flutter integration tests in all packages with integration tests.
    packageFilters:
      flutter: true
      dirExists: integration_test
      ignore: "*example*"
